### ISSUE TITLE
Custom range option

### ISSUE THREAD

**Issue by nikkii94** [wakirin/litepicker-module-ranges#10] opened 2021-01-02 19:08 UTC
Hello!

I'm trying to replace the daterangepicker lib with Litepicker in one of my project, and I have a few questions.
Example: https://www.daterangepicker.com/#example4 

Am I able to add a Custom Range label, and when the user clicks on it, then he could pick the range from the calendars like in the example? 
And also, is there a way to mark a predefined range if the start date and end date matches? Or if it doesn't, then mark the custom label.

Thank you!

**Comment by wakirin** [comment] 2021-01-20 11:48
duplicate of #6

**Closed by wakirin** 2021-01-20 11:48 UTC
